bash bash/NewMethod/subTableCT/NewMethod_Biomedical_top100_cluster30_CT.sh
bash bash/NewMethod/subTableCT/NewMethod_GoogleNews_top100_cluster30_CT.sh
bash bash/NewMethod/subTableCT/NewMethod_SearchSnippets_top100_cluster30_CT.sh
bash bash/NewMethod/subTableCT/NewMethod_StackOverflow_top100_cluster30_CT.sh

