bash bash/NewMethod/mainTabletop50/NewMethod_Biomedical_top50_cluster30_main.sh
bash bash/NewMethod/mainTabletop50/NewMethod_GoogleNews_top50_cluster30_main.sh
bash bash/NewMethod/mainTabletop50/NewMethod_SearchSnippets_top50_cluster30_main.sh
bash bash/NewMethod/mainTabletop50/NewMethod_StackOverflow_top50_cluster30_main.sh

